### ISSUE TITLE
DLL load failed for ffpyplayer

### ISSUE THREAD

**Issue by Isquare1** [matham/thorcam#4] opened 2020-11-06 00:05 UTC
Hi, I would love to use your code to interface my thorlabs camera, but unfortunately I get the following: 

```
from thorcam.camera import ThorCam
Traceback (most recent call last):

  File "<ipython-input-140-9cae979d703d>", line 1, in <module>
    from thorcam.camera import ThorCam

  File "C:\Users\user\anaconda3\lib\site-packages\thorcam\camera.py", line 34, in <module>
    from ffpyplayer.pic import Image

ImportError: DLL load failed: The file cannot be accessed by the system.
```

I use Python 3.7 (Anaconda), Spyder IDE, Windows 10, 64-bit. I have Visual Studio installed. I have installed the drivers for my camera, and they are recognised by other packages. 
Do I have to downgrade my Python version in order to match the DLLs with what the package is expecting? 
PS My programming knowledge in this area is pretty limited, apologies.

**Comment by matham** [comment] 2020-11-06 00:23
The issue is that you're mixing pip install with anaconda install. If you're using anaconda, you need to install ffpyplayer and thorcam dependencies through anaconda and then install thorcam. That way the important thorcam's dependencies will be installed through conda already.

It should be something like

```sh
conda install ffpyplayer pythonnet numpy -c conda-forge
pip install thorcam
```

Also, please make sure to do this in a new and clean conda environment (i.e. not in the base environment and in one created from fresh), otherwise you'll run into issues from the previous install.

**Comment by Isquare1** [comment] 2020-11-14 14:23
Thanks so much, this worked perfect, ffpyplayer is not imported :)

**Closed as completed** 2021-01-19 23:42 UTC
